name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PEM }}" > ~/.ssh/ec2.pem
        chmod 600 ~/.ssh/ec2.pem
        echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - name: Set up environment variables
      run: |
        ssh -i ~/.ssh/ec2.pem ec2-user@${{ secrets.EC2_ADDRESS }} "bash -s" << 'EOF'
        if [ ! -f ~/moving-be/.env ]; then
          touch ~/moving-be/.env
        fi
        echo "${{ secrets.ENV_FILE }}" > ~/moving-be/.env
        cat ~/moving-be/.env
        EOF

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2.pem -T ec2-user@${{ secrets.EC2_ADDRESS }} << 'EOF'
          cd ~/moving-be
          git fetch origin main
          git reset --hard origin/main
          npm install
          npm audit fix --force
          npm run build
          
          # 클러스터 모드로 앱이 실행되어 있지 않다면 처음 실행
          if ! pm2 list | grep -q "my-app"; then
            pm2 start dist/app.js --name my-app -i max
          else
            # 무중단 배포를 위한 reload
            pm2 reload my-app --update-env
          fi
          
          # 로그 확인
          pm2 logs my-app --lines 10
        EOF
